In [1]:
import pandas as pd

In [6]:
fname_test = '/home/jupyter/__output_clean/luad1/scvi/cell_level_pred/cell_pred_test.csv'
fname_train = '/home/jupyter/__output_clean/luad1/scvi/cell_level_pred/cell_pred_train.csv'
df_test = pd.read_csv(fname_test)
df_train = pd.read_csv(fname_train)

In [7]:
fname_test

'/home/jupyter/__output_clean/luad1/scvi/cell_level_pred/cell_pred_test.csv'

In [11]:
df_test.groupby('sample_id').count()

,Unnamed: 0,group_id,leiden,label,batch,n_genes_by_counts,total_counts,n_genes,_scvi_batch,_scvi_labels,pred,pred_score
sample_id,,,,,,,,,,,,
kim_EBUS_06,1186,1186,1186,1186,1186,1186,1186,1186,1186,1186,1186,1186
kim_LUNG_T19,222,222,222,222,222,222,222,222,222,222,222,222
kim_LUNG_T34,2374,2374,2374,2374,2374,2374,2374,2374,2374,2374,2374,2374
maynard_LT_S66,229,229,229,229,229,229,229,229,229,229,229,229
qian_P4_BT1295,321,321,321,321,321,321,321,321,321,321,321,321

In [12]:
df_train.groupby('sample_id').count()

,Unnamed: 0,group_id,leiden,label,batch,n_genes_by_counts,total_counts,n_genes,_scvi_batch,_scvi_labels,pred,pred_score
sample_id,,,,,,,,,,,,
kim_BRONCHO_58,460,460,460,460,460,460,460,460,460,460,460,460
kim_EBUS_28,4640,4640,4640,4640,4640,4640,4640,4640,4640,4640,4640,4640
kim_EBUS_49,114,114,114,114,114,114,114,114,114,114,114,114
kim_LUNG_T06,100,100,100,100,100,100,100,100,100,100,100,100
kim_LUNG_T08,42,42,42,42,42,42,42,42,42,42,42,42
kim_LUNG_T09,5,5,5,5,5,5,5,5,5,5,5,5
kim_LUNG_T18,1002,1002,1002,1002,1002,1002,1002,1002,1002,1002,1002,1002
kim_LUNG_T20,434,434,434,434,434,434,434,434,434,434,434,434
kim_LUNG_T25,223,223,223,223,223,223,223,223,223,223,223,223
kim_LUNG_T28,984,984,984,984,984,984,984,984,984,984,984,984
kim_LUNG_T30,784,784,784,784,784,784,784,784,784,784,784,784
kim_LUNG_T31,182,182,182,182,182,182,182,182,182,182,182,182
maynard_LT_S65,5,5,5,5,5,5,5,5,5,5,5,5
qian_P4_BT1296,859,859,859,859,859,859,859,859,859,859,859,859
qian_P4_BT1297,1520,1520,1520,1520,1520,1520,1520,1520,1520,1520,1520,1520
qian_P6_BT1375,346,346,346,346,346,346,346,346,346,346,346,346
qian_P6_BT1376,528,528,528,528,528,528,528,528,528,528,528,528
qian_P6_BT1377,234,234,234,234,234,234,234,234,234,234,234,234